// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/lminimum/LiteDock/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockContainerRepo is a mock of ContainerRepo interface.
type MockContainerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContainerRepoMockRecorder
	isgomock struct{}
}

// MockContainerRepoMockRecorder is the mock recorder for MockContainerRepo.
type MockContainerRepoMockRecorder struct {
	mock *MockContainerRepo
}

// NewMockContainerRepo creates a new mock instance.
func NewMockContainerRepo(ctrl *gomock.Controller) *MockContainerRepo {
	mock := &MockContainerRepo{ctrl: ctrl}
	mock.recorder = &MockContainerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerRepo) EXPECT() *MockContainerRepoMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockContainerRepo) CountAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockContainerRepoMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockContainerRepo)(nil).CountAll), ctx)
}

// CountByStatus mocks base method.
func (m *MockContainerRepo) CountByStatus(ctx context.Context, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockContainerRepoMockRecorder) CountByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockContainerRepo)(nil).CountByStatus), ctx, status)
}

// DeleteByMachine mocks base method.
func (m *MockContainerRepo) DeleteByMachine(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMachine", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMachine indicates an expected call of DeleteByMachine.
func (mr *MockContainerRepoMockRecorder) DeleteByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMachine", reflect.TypeOf((*MockContainerRepo)(nil).DeleteByMachine), ctx, machineID)
}

// Get mocks base method.
func (m *MockContainerRepo) Get(arg0 context.Context, arg1 string) (*entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContainerRepoMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContainerRepo)(nil).Get), arg0, arg1)
}

// IsCacheValid mocks base method.
func (m *MockContainerRepo) IsCacheValid(ctx context.Context, machineID string, maxAge time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheValid", ctx, machineID, maxAge)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCacheValid indicates an expected call of IsCacheValid.
func (mr *MockContainerRepoMockRecorder) IsCacheValid(ctx, machineID, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheValid", reflect.TypeOf((*MockContainerRepo)(nil).IsCacheValid), ctx, machineID, maxAge)
}

// List mocks base method.
func (m *MockContainerRepo) List(arg0 context.Context) ([]entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockContainerRepoMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContainerRepo)(nil).List), arg0)
}

// ListByMachine mocks base method.
func (m *MockContainerRepo) ListByMachine(ctx context.Context, machineID string) ([]entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineID)
	ret0, _ := ret[0].([]entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockContainerRepoMockRecorder) ListByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockContainerRepo)(nil).ListByMachine), ctx, machineID)
}

// UpsertBatch mocks base method.
func (m *MockContainerRepo) UpsertBatch(ctx context.Context, machineID string, containers []entity.Container) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, machineID, containers)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockContainerRepoMockRecorder) UpsertBatch(ctx, machineID, containers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockContainerRepo)(nil).UpsertBatch), ctx, machineID, containers)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockUserRepo) CountUsers(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockUserRepoMockRecorder) CountUsers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockUserRepo)(nil).CountUsers), arg0)
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(arg0 context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockUserRepo) DeleteUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepoMockRecorder) DeleteUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepo)(nil).DeleteUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepo) GetUserByEmail(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepoMockRecorder) GetUserByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), arg0, arg1)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepo) GetUserByUsername(arg0 context.Context, arg1 string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0, arg1)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepoMockRecorder) GetUserByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepo)(nil).GetUserByUsername), arg0, arg1)
}

// UpdatePassword mocks base method.
func (m *MockUserRepo) UpdatePassword(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserRepoMockRecorder) UpdatePassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserRepo)(nil).UpdatePassword), arg0, arg1, arg2)
}

// UpdateUser mocks base method.
func (m *MockUserRepo) UpdateUser(arg0 context.Context, arg1 *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepoMockRecorder) UpdateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepo)(nil).UpdateUser), arg0, arg1)
}

// VerifyPassword mocks base method.
func (m *MockUserRepo) VerifyPassword(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockUserRepoMockRecorder) VerifyPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockUserRepo)(nil).VerifyPassword), arg0, arg1, arg2)
}

// MockRemoteMachineRepo is a mock of RemoteMachineRepo interface.
type MockRemoteMachineRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteMachineRepoMockRecorder
	isgomock struct{}
}

// MockRemoteMachineRepoMockRecorder is the mock recorder for MockRemoteMachineRepo.
type MockRemoteMachineRepoMockRecorder struct {
	mock *MockRemoteMachineRepo
}

// NewMockRemoteMachineRepo creates a new mock instance.
func NewMockRemoteMachineRepo(ctrl *gomock.Controller) *MockRemoteMachineRepo {
	mock := &MockRemoteMachineRepo{ctrl: ctrl}
	mock.recorder = &MockRemoteMachineRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteMachineRepo) EXPECT() *MockRemoteMachineRepoMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRemoteMachineRepo) Count(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRemoteMachineRepoMockRecorder) Count(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRemoteMachineRepo)(nil).Count), arg0)
}

// Create mocks base method.
func (m *MockRemoteMachineRepo) Create(arg0 context.Context, arg1 *entity.RemoteMachine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRemoteMachineRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRemoteMachineRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockRemoteMachineRepo) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRemoteMachineRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRemoteMachineRepo)(nil).Delete), arg0, arg1)
}

// GetByHost mocks base method.
func (m *MockRemoteMachineRepo) GetByHost(arg0 context.Context, arg1 string) (*entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHost", arg0, arg1)
	ret0, _ := ret[0].(*entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHost indicates an expected call of GetByHost.
func (mr *MockRemoteMachineRepoMockRecorder) GetByHost(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHost", reflect.TypeOf((*MockRemoteMachineRepo)(nil).GetByHost), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockRemoteMachineRepo) GetByID(arg0 context.Context, arg1 string) (*entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRemoteMachineRepoMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRemoteMachineRepo)(nil).GetByID), arg0, arg1)
}

// List mocks base method.
func (m *MockRemoteMachineRepo) List(arg0 context.Context) ([]entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRemoteMachineRepoMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRemoteMachineRepo)(nil).List), arg0)
}

// Update mocks base method.
func (m *MockRemoteMachineRepo) Update(arg0 context.Context, arg1 *entity.RemoteMachine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRemoteMachineRepoMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRemoteMachineRepo)(nil).Update), arg0, arg1)
}

// UpdateStatus mocks base method.
func (m *MockRemoteMachineRepo) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRemoteMachineRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRemoteMachineRepo)(nil).UpdateStatus), ctx, id, status)
}

// MockSystemMetricsRepo is a mock of SystemMetricsRepo interface.
type MockSystemMetricsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMetricsRepoMockRecorder
	isgomock struct{}
}

// MockSystemMetricsRepoMockRecorder is the mock recorder for MockSystemMetricsRepo.
type MockSystemMetricsRepoMockRecorder struct {
	mock *MockSystemMetricsRepo
}

// NewMockSystemMetricsRepo creates a new mock instance.
func NewMockSystemMetricsRepo(ctrl *gomock.Controller) *MockSystemMetricsRepo {
	mock := &MockSystemMetricsRepo{ctrl: ctrl}
	mock.recorder = &MockSystemMetricsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMetricsRepo) EXPECT() *MockSystemMetricsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockSystemMetricsRepo) Create(ctx context.Context, m *entity.SystemMetric) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSystemMetricsRepoMockRecorder) Create(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSystemMetricsRepo)(nil).Create), ctx, m)
}

// DeleteOlderThan mocks base method.
func (m *MockSystemMetricsRepo) DeleteOlderThan(ctx context.Context, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOlderThan", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOlderThan indicates an expected call of DeleteOlderThan.
func (mr *MockSystemMetricsRepoMockRecorder) DeleteOlderThan(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOlderThan", reflect.TypeOf((*MockSystemMetricsRepo)(nil).DeleteOlderThan), ctx, before)
}

// GetHistory mocks base method.
func (m *MockSystemMetricsRepo) GetHistory(ctx context.Context, since time.Time) ([]entity.SystemMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, since)
	ret0, _ := ret[0].([]entity.SystemMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockSystemMetricsRepoMockRecorder) GetHistory(ctx, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockSystemMetricsRepo)(nil).GetHistory), ctx, since)
}

// PruneToCount mocks base method.
func (m *MockSystemMetricsRepo) PruneToCount(ctx context.Context, maxCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneToCount", ctx, maxCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneToCount indicates an expected call of PruneToCount.
func (mr *MockSystemMetricsRepoMockRecorder) PruneToCount(ctx, maxCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneToCount", reflect.TypeOf((*MockSystemMetricsRepo)(nil).PruneToCount), ctx, maxCount)
}

// MockNetworkRepo is a mock of NetworkRepo interface.
type MockNetworkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkRepoMockRecorder
	isgomock struct{}
}

// MockNetworkRepoMockRecorder is the mock recorder for MockNetworkRepo.
type MockNetworkRepoMockRecorder struct {
	mock *MockNetworkRepo
}

// NewMockNetworkRepo creates a new mock instance.
func NewMockNetworkRepo(ctrl *gomock.Controller) *MockNetworkRepo {
	mock := &MockNetworkRepo{ctrl: ctrl}
	mock.recorder = &MockNetworkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkRepo) EXPECT() *MockNetworkRepoMockRecorder {
	return m.recorder
}

// DeleteByMachine mocks base method.
func (m *MockNetworkRepo) DeleteByMachine(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMachine", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMachine indicates an expected call of DeleteByMachine.
func (mr *MockNetworkRepoMockRecorder) DeleteByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMachine", reflect.TypeOf((*MockNetworkRepo)(nil).DeleteByMachine), ctx, machineID)
}

// GetByName mocks base method.
func (m *MockNetworkRepo) GetByName(ctx context.Context, machineID, name string) (*entity.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, machineID, name)
	ret0, _ := ret[0].(*entity.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockNetworkRepoMockRecorder) GetByName(ctx, machineID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockNetworkRepo)(nil).GetByName), ctx, machineID, name)
}

// IsCacheValid mocks base method.
func (m *MockNetworkRepo) IsCacheValid(ctx context.Context, machineID string, maxAge time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheValid", ctx, machineID, maxAge)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCacheValid indicates an expected call of IsCacheValid.
func (mr *MockNetworkRepoMockRecorder) IsCacheValid(ctx, machineID, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheValid", reflect.TypeOf((*MockNetworkRepo)(nil).IsCacheValid), ctx, machineID, maxAge)
}

// ListByMachine mocks base method.
func (m *MockNetworkRepo) ListByMachine(ctx context.Context, machineID string) ([]entity.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineID)
	ret0, _ := ret[0].([]entity.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockNetworkRepoMockRecorder) ListByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockNetworkRepo)(nil).ListByMachine), ctx, machineID)
}

// UpsertBatch mocks base method.
func (m *MockNetworkRepo) UpsertBatch(ctx context.Context, machineID string, networks []entity.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, machineID, networks)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockNetworkRepoMockRecorder) UpsertBatch(ctx, machineID, networks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockNetworkRepo)(nil).UpsertBatch), ctx, machineID, networks)
}

// MockVolumeRepo is a mock of VolumeRepo interface.
type MockVolumeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeRepoMockRecorder
	isgomock struct{}
}

// MockVolumeRepoMockRecorder is the mock recorder for MockVolumeRepo.
type MockVolumeRepoMockRecorder struct {
	mock *MockVolumeRepo
}

// NewMockVolumeRepo creates a new mock instance.
func NewMockVolumeRepo(ctrl *gomock.Controller) *MockVolumeRepo {
	mock := &MockVolumeRepo{ctrl: ctrl}
	mock.recorder = &MockVolumeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeRepo) EXPECT() *MockVolumeRepoMockRecorder {
	return m.recorder
}

// DeleteByMachine mocks base method.
func (m *MockVolumeRepo) DeleteByMachine(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMachine", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMachine indicates an expected call of DeleteByMachine.
func (mr *MockVolumeRepoMockRecorder) DeleteByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMachine", reflect.TypeOf((*MockVolumeRepo)(nil).DeleteByMachine), ctx, machineID)
}

// GetByName mocks base method.
func (m *MockVolumeRepo) GetByName(ctx context.Context, machineID, name string) (*entity.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, machineID, name)
	ret0, _ := ret[0].(*entity.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockVolumeRepoMockRecorder) GetByName(ctx, machineID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockVolumeRepo)(nil).GetByName), ctx, machineID, name)
}

// IsCacheValid mocks base method.
func (m *MockVolumeRepo) IsCacheValid(ctx context.Context, machineID string, maxAge time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheValid", ctx, machineID, maxAge)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCacheValid indicates an expected call of IsCacheValid.
func (mr *MockVolumeRepoMockRecorder) IsCacheValid(ctx, machineID, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheValid", reflect.TypeOf((*MockVolumeRepo)(nil).IsCacheValid), ctx, machineID, maxAge)
}

// ListByMachine mocks base method.
func (m *MockVolumeRepo) ListByMachine(ctx context.Context, machineID string) ([]entity.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineID)
	ret0, _ := ret[0].([]entity.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockVolumeRepoMockRecorder) ListByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockVolumeRepo)(nil).ListByMachine), ctx, machineID)
}

// UpsertBatch mocks base method.
func (m *MockVolumeRepo) UpsertBatch(ctx context.Context, machineID string, volumes []entity.Volume) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, machineID, volumes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockVolumeRepoMockRecorder) UpsertBatch(ctx, machineID, volumes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockVolumeRepo)(nil).UpsertBatch), ctx, machineID, volumes)
}

// MockImageRepo is a mock of ImageRepo interface.
type MockImageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockImageRepoMockRecorder
	isgomock struct{}
}

// MockImageRepoMockRecorder is the mock recorder for MockImageRepo.
type MockImageRepoMockRecorder struct {
	mock *MockImageRepo
}

// NewMockImageRepo creates a new mock instance.
func NewMockImageRepo(ctrl *gomock.Controller) *MockImageRepo {
	mock := &MockImageRepo{ctrl: ctrl}
	mock.recorder = &MockImageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageRepo) EXPECT() *MockImageRepoMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockImageRepo) CountAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockImageRepoMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockImageRepo)(nil).CountAll), ctx)
}

// DeleteByID mocks base method.
func (m *MockImageRepo) DeleteByID(ctx context.Context, machineID, imageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, machineID, imageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockImageRepoMockRecorder) DeleteByID(ctx, machineID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockImageRepo)(nil).DeleteByID), ctx, machineID, imageID)
}

// DeleteByMachine mocks base method.
func (m *MockImageRepo) DeleteByMachine(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMachine", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMachine indicates an expected call of DeleteByMachine.
func (mr *MockImageRepoMockRecorder) DeleteByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMachine", reflect.TypeOf((*MockImageRepo)(nil).DeleteByMachine), ctx, machineID)
}

// GetByID mocks base method.
func (m *MockImageRepo) GetByID(ctx context.Context, machineID, imageID string) (*entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, machineID, imageID)
	ret0, _ := ret[0].(*entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockImageRepoMockRecorder) GetByID(ctx, machineID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockImageRepo)(nil).GetByID), ctx, machineID, imageID)
}

// IsCacheValid mocks base method.
func (m *MockImageRepo) IsCacheValid(ctx context.Context, machineID string, maxAge time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheValid", ctx, machineID, maxAge)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCacheValid indicates an expected call of IsCacheValid.
func (mr *MockImageRepoMockRecorder) IsCacheValid(ctx, machineID, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheValid", reflect.TypeOf((*MockImageRepo)(nil).IsCacheValid), ctx, machineID, maxAge)
}

// ListByMachine mocks base method.
func (m *MockImageRepo) ListByMachine(ctx context.Context, machineID string) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineID)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockImageRepoMockRecorder) ListByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockImageRepo)(nil).ListByMachine), ctx, machineID)
}

// UpsertBatch mocks base method.
func (m *MockImageRepo) UpsertBatch(ctx context.Context, machineID string, images []entity.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, machineID, images)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockImageRepoMockRecorder) UpsertBatch(ctx, machineID, images any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockImageRepo)(nil).UpsertBatch), ctx, machineID, images)
}

// MockComposeRepo is a mock of ComposeRepo interface.
type MockComposeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockComposeRepoMockRecorder
	isgomock struct{}
}

// MockComposeRepoMockRecorder is the mock recorder for MockComposeRepo.
type MockComposeRepoMockRecorder struct {
	mock *MockComposeRepo
}

// NewMockComposeRepo creates a new mock instance.
func NewMockComposeRepo(ctrl *gomock.Controller) *MockComposeRepo {
	mock := &MockComposeRepo{ctrl: ctrl}
	mock.recorder = &MockComposeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComposeRepo) EXPECT() *MockComposeRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComposeRepo) Create(ctx context.Context, composeFile *entity.ComposeFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, composeFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockComposeRepoMockRecorder) Create(ctx, composeFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComposeRepo)(nil).Create), ctx, composeFile)
}

// DeleteByID mocks base method.
func (m *MockComposeRepo) DeleteByID(ctx context.Context, machineID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, machineID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockComposeRepoMockRecorder) DeleteByID(ctx, machineID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockComposeRepo)(nil).DeleteByID), ctx, machineID, id)
}

// DeleteByMachine mocks base method.
func (m *MockComposeRepo) DeleteByMachine(ctx context.Context, machineID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMachine", ctx, machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMachine indicates an expected call of DeleteByMachine.
func (mr *MockComposeRepoMockRecorder) DeleteByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMachine", reflect.TypeOf((*MockComposeRepo)(nil).DeleteByMachine), ctx, machineID)
}

// GetByID mocks base method.
func (m *MockComposeRepo) GetByID(ctx context.Context, machineID, id string) (*entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, machineID, id)
	ret0, _ := ret[0].(*entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockComposeRepoMockRecorder) GetByID(ctx, machineID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockComposeRepo)(nil).GetByID), ctx, machineID, id)
}

// GetByProjectName mocks base method.
func (m *MockComposeRepo) GetByProjectName(ctx context.Context, machineID, projectName string) (*entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectName", ctx, machineID, projectName)
	ret0, _ := ret[0].(*entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectName indicates an expected call of GetByProjectName.
func (mr *MockComposeRepoMockRecorder) GetByProjectName(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectName", reflect.TypeOf((*MockComposeRepo)(nil).GetByProjectName), ctx, machineID, projectName)
}

// IsCacheValid mocks base method.
func (m *MockComposeRepo) IsCacheValid(ctx context.Context, machineID string, maxAge time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheValid", ctx, machineID, maxAge)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCacheValid indicates an expected call of IsCacheValid.
func (mr *MockComposeRepoMockRecorder) IsCacheValid(ctx, machineID, maxAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheValid", reflect.TypeOf((*MockComposeRepo)(nil).IsCacheValid), ctx, machineID, maxAge)
}

// ListByMachine mocks base method.
func (m *MockComposeRepo) ListByMachine(ctx context.Context, machineID string) ([]entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMachine", ctx, machineID)
	ret0, _ := ret[0].([]entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMachine indicates an expected call of ListByMachine.
func (mr *MockComposeRepoMockRecorder) ListByMachine(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMachine", reflect.TypeOf((*MockComposeRepo)(nil).ListByMachine), ctx, machineID)
}

// Update mocks base method.
func (m *MockComposeRepo) Update(ctx context.Context, composeFile *entity.ComposeFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, composeFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockComposeRepoMockRecorder) Update(ctx, composeFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComposeRepo)(nil).Update), ctx, composeFile)
}

// UpsertBatch mocks base method.
func (m *MockComposeRepo) UpsertBatch(ctx context.Context, composeFiles []entity.ComposeFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, composeFiles)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockComposeRepoMockRecorder) UpsertBatch(ctx, composeFiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockComposeRepo)(nil).UpsertBatch), ctx, composeFiles)
}
