// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	image "github.com/docker/docker/api/types/image"
	entity "github.com/lminimum/LiteDock/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockContainer is a mock of Container interface.
type MockContainer struct {
	ctrl     *gomock.Controller
	recorder *MockContainerMockRecorder
	isgomock struct{}
}

// MockContainerMockRecorder is the mock recorder for MockContainer.
type MockContainerMockRecorder struct {
	mock *MockContainer
}

// NewMockContainer creates a new mock instance.
func NewMockContainer(ctrl *gomock.Controller) *MockContainer {
	mock := &MockContainer{ctrl: ctrl}
	mock.recorder = &MockContainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainer) EXPECT() *MockContainerMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockContainer) CountAll(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockContainerMockRecorder) CountAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockContainer)(nil).CountAll), ctx)
}

// CountByStatus mocks base method.
func (m *MockContainer) CountByStatus(ctx context.Context, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockContainerMockRecorder) CountByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockContainer)(nil).CountByStatus), ctx, status)
}

// Get mocks base method.
func (m *MockContainer) Get(ctx context.Context, id string) (*entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockContainerMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContainer)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockContainer) List(ctx context.Context) ([]entity.Container, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Container)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockContainerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContainer)(nil).List), ctx)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
	isgomock struct{}
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// GetCurrentUser mocks base method.
func (m *MockAuth) GetCurrentUser(ctx context.Context, token string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUser", ctx, token)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUser indicates an expected call of GetCurrentUser.
func (mr *MockAuthMockRecorder) GetCurrentUser(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUser", reflect.TypeOf((*MockAuth)(nil).GetCurrentUser), ctx, token)
}

// IsSetupComplete mocks base method.
func (m *MockAuth) IsSetupComplete(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSetupComplete", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSetupComplete indicates an expected call of IsSetupComplete.
func (mr *MockAuthMockRecorder) IsSetupComplete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSetupComplete", reflect.TypeOf((*MockAuth)(nil).IsSetupComplete), ctx)
}

// Login mocks base method.
func (m *MockAuth) Login(ctx context.Context, username, password string) (string, *entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*entity.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), ctx, username, password)
}

// RefreshToken mocks base method.
func (m *MockAuth) RefreshToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuth)(nil).RefreshToken), ctx, token)
}

// Register mocks base method.
func (m *MockAuth) Register(ctx context.Context, username, email, password, role string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password, role)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthMockRecorder) Register(ctx, username, email, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuth)(nil).Register), ctx, username, email, password, role)
}

// MockRemoteMachine is a mock of RemoteMachine interface.
type MockRemoteMachine struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteMachineMockRecorder
	isgomock struct{}
}

// MockRemoteMachineMockRecorder is the mock recorder for MockRemoteMachine.
type MockRemoteMachineMockRecorder struct {
	mock *MockRemoteMachine
}

// NewMockRemoteMachine creates a new mock instance.
func NewMockRemoteMachine(ctrl *gomock.Controller) *MockRemoteMachine {
	mock := &MockRemoteMachine{ctrl: ctrl}
	mock.recorder = &MockRemoteMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteMachine) EXPECT() *MockRemoteMachineMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRemoteMachine) Create(ctx context.Context, machine *entity.RemoteMachine) (*entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, machine)
	ret0, _ := ret[0].(*entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRemoteMachineMockRecorder) Create(ctx, machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRemoteMachine)(nil).Create), ctx, machine)
}

// Delete mocks base method.
func (m *MockRemoteMachine) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRemoteMachineMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRemoteMachine)(nil).Delete), ctx, id)
}

// GetByHost mocks base method.
func (m *MockRemoteMachine) GetByHost(ctx context.Context, host string) (*entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHost", ctx, host)
	ret0, _ := ret[0].(*entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHost indicates an expected call of GetByHost.
func (mr *MockRemoteMachineMockRecorder) GetByHost(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHost", reflect.TypeOf((*MockRemoteMachine)(nil).GetByHost), ctx, host)
}

// GetByID mocks base method.
func (m *MockRemoteMachine) GetByID(ctx context.Context, id string) (*entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRemoteMachineMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRemoteMachine)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRemoteMachine) List(ctx context.Context) ([]entity.RemoteMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.RemoteMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRemoteMachineMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRemoteMachine)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockRemoteMachine) Update(ctx context.Context, machine *entity.RemoteMachine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, machine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRemoteMachineMockRecorder) Update(ctx, machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRemoteMachine)(nil).Update), ctx, machine)
}

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
	isgomock struct{}
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// CreateNetwork mocks base method.
func (m *MockNetwork) CreateNetwork(ctx context.Context, machineID, name, driver string) (*entity.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, machineID, name, driver)
	ret0, _ := ret[0].(*entity.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockNetworkMockRecorder) CreateNetwork(ctx, machineID, name, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockNetwork)(nil).CreateNetwork), ctx, machineID, name, driver)
}

// DeleteNetwork mocks base method.
func (m *MockNetwork) DeleteNetwork(ctx context.Context, machineID, networkName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", ctx, machineID, networkName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockNetworkMockRecorder) DeleteNetwork(ctx, machineID, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockNetwork)(nil).DeleteNetwork), ctx, machineID, networkName)
}

// InspectNetwork mocks base method.
func (m *MockNetwork) InspectNetwork(ctx context.Context, machineID, networkName string) (*entity.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectNetwork", ctx, machineID, networkName)
	ret0, _ := ret[0].(*entity.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectNetwork indicates an expected call of InspectNetwork.
func (mr *MockNetworkMockRecorder) InspectNetwork(ctx, machineID, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectNetwork", reflect.TypeOf((*MockNetwork)(nil).InspectNetwork), ctx, machineID, networkName)
}

// ListNetworks mocks base method.
func (m *MockNetwork) ListNetworks(ctx context.Context, machineID string) ([]entity.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", ctx, machineID)
	ret0, _ := ret[0].([]entity.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockNetworkMockRecorder) ListNetworks(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockNetwork)(nil).ListNetworks), ctx, machineID)
}

// MockVolume is a mock of Volume interface.
type MockVolume struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeMockRecorder
	isgomock struct{}
}

// MockVolumeMockRecorder is the mock recorder for MockVolume.
type MockVolumeMockRecorder struct {
	mock *MockVolume
}

// NewMockVolume creates a new mock instance.
func NewMockVolume(ctrl *gomock.Controller) *MockVolume {
	mock := &MockVolume{ctrl: ctrl}
	mock.recorder = &MockVolumeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolume) EXPECT() *MockVolumeMockRecorder {
	return m.recorder
}

// CreateVolume mocks base method.
func (m *MockVolume) CreateVolume(ctx context.Context, machineID, name, driver string) (*entity.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", ctx, machineID, name, driver)
	ret0, _ := ret[0].(*entity.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockVolumeMockRecorder) CreateVolume(ctx, machineID, name, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockVolume)(nil).CreateVolume), ctx, machineID, name, driver)
}

// DeleteVolume mocks base method.
func (m *MockVolume) DeleteVolume(ctx context.Context, machineID, volumeName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", ctx, machineID, volumeName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockVolumeMockRecorder) DeleteVolume(ctx, machineID, volumeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockVolume)(nil).DeleteVolume), ctx, machineID, volumeName)
}

// InspectVolume mocks base method.
func (m *MockVolume) InspectVolume(ctx context.Context, machineID, volumeName string) (*entity.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectVolume", ctx, machineID, volumeName)
	ret0, _ := ret[0].(*entity.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectVolume indicates an expected call of InspectVolume.
func (mr *MockVolumeMockRecorder) InspectVolume(ctx, machineID, volumeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectVolume", reflect.TypeOf((*MockVolume)(nil).InspectVolume), ctx, machineID, volumeName)
}

// ListVolumes mocks base method.
func (m *MockVolume) ListVolumes(ctx context.Context, machineID string) ([]entity.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", ctx, machineID)
	ret0, _ := ret[0].([]entity.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockVolumeMockRecorder) ListVolumes(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockVolume)(nil).ListVolumes), ctx, machineID)
}

// MockImage is a mock of Image interface.
type MockImage struct {
	ctrl     *gomock.Controller
	recorder *MockImageMockRecorder
	isgomock struct{}
}

// MockImageMockRecorder is the mock recorder for MockImage.
type MockImageMockRecorder struct {
	mock *MockImage
}

// NewMockImage creates a new mock instance.
func NewMockImage(ctrl *gomock.Controller) *MockImage {
	mock := &MockImage{ctrl: ctrl}
	mock.recorder = &MockImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImage) EXPECT() *MockImageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockImage) Delete(ctx context.Context, machineID, imageID string) ([]image.DeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, machineID, imageID)
	ret0, _ := ret[0].([]image.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockImageMockRecorder) Delete(ctx, machineID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImage)(nil).Delete), ctx, machineID, imageID)
}

// Inspect mocks base method.
func (m *MockImage) Inspect(ctx context.Context, machineID, imageID string) (*entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, machineID, imageID)
	ret0, _ := ret[0].(*entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockImageMockRecorder) Inspect(ctx, machineID, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockImage)(nil).Inspect), ctx, machineID, imageID)
}

// List mocks base method.
func (m *MockImage) List(ctx context.Context, machineID string) ([]entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, machineID)
	ret0, _ := ret[0].([]entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockImageMockRecorder) List(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockImage)(nil).List), ctx, machineID)
}

// Prune mocks base method.
func (m *MockImage) Prune(ctx context.Context, machineID string) (*image.PruneReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, machineID)
	ret0, _ := ret[0].(*image.PruneReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockImageMockRecorder) Prune(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockImage)(nil).Prune), ctx, machineID)
}

// Pull mocks base method.
func (m *MockImage) Pull(ctx context.Context, machineID, repository, tag string) (*entity.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, machineID, repository, tag)
	ret0, _ := ret[0].(*entity.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockImageMockRecorder) Pull(ctx, machineID, repository, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockImage)(nil).Pull), ctx, machineID, repository, tag)
}

// MockCompose is a mock of Compose interface.
type MockCompose struct {
	ctrl     *gomock.Controller
	recorder *MockComposeMockRecorder
	isgomock struct{}
}

// MockComposeMockRecorder is the mock recorder for MockCompose.
type MockComposeMockRecorder struct {
	mock *MockCompose
}

// NewMockCompose creates a new mock instance.
func NewMockCompose(ctrl *gomock.Controller) *MockCompose {
	mock := &MockCompose{ctrl: ctrl}
	mock.recorder = &MockComposeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompose) EXPECT() *MockComposeMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockCompose) Build(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockComposeMockRecorder) Build(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockCompose)(nil).Build), ctx, machineID, projectName)
}

// Create mocks base method.
func (m *MockCompose) Create(ctx context.Context, machineID, name, yamlContent, filePath string) (*entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, machineID, name, yamlContent, filePath)
	ret0, _ := ret[0].(*entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockComposeMockRecorder) Create(ctx, machineID, name, yamlContent, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompose)(nil).Create), ctx, machineID, name, yamlContent, filePath)
}

// Delete mocks base method.
func (m *MockCompose) Delete(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockComposeMockRecorder) Delete(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompose)(nil).Delete), ctx, machineID, projectName)
}

// Down mocks base method.
func (m *MockCompose) Down(ctx context.Context, machineID, projectName string, volumes bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Down", ctx, machineID, projectName, volumes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Down indicates an expected call of Down.
func (mr *MockComposeMockRecorder) Down(ctx, machineID, projectName, volumes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Down", reflect.TypeOf((*MockCompose)(nil).Down), ctx, machineID, projectName, volumes)
}

// Get mocks base method.
func (m *MockCompose) Get(ctx context.Context, machineID, projectName string) (*entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, machineID, projectName)
	ret0, _ := ret[0].(*entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComposeMockRecorder) Get(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompose)(nil).Get), ctx, machineID, projectName)
}

// List mocks base method.
func (m *MockCompose) List(ctx context.Context, machineID string) ([]entity.ComposeFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, machineID)
	ret0, _ := ret[0].([]entity.ComposeFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockComposeMockRecorder) List(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCompose)(nil).List), ctx, machineID)
}

// Logs mocks base method.
func (m *MockCompose) Logs(ctx context.Context, machineID, projectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, machineID, projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockComposeMockRecorder) Logs(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockCompose)(nil).Logs), ctx, machineID, projectName)
}

// Ps mocks base method.
func (m *MockCompose) Ps(ctx context.Context, machineID, projectName string) ([]entity.ComposeService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ps", ctx, machineID, projectName)
	ret0, _ := ret[0].([]entity.ComposeService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ps indicates an expected call of Ps.
func (mr *MockComposeMockRecorder) Ps(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ps", reflect.TypeOf((*MockCompose)(nil).Ps), ctx, machineID, projectName)
}

// Restart mocks base method.
func (m *MockCompose) Restart(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockComposeMockRecorder) Restart(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockCompose)(nil).Restart), ctx, machineID, projectName)
}

// Start mocks base method.
func (m *MockCompose) Start(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockComposeMockRecorder) Start(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCompose)(nil).Start), ctx, machineID, projectName)
}

// Stop mocks base method.
func (m *MockCompose) Stop(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockComposeMockRecorder) Stop(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCompose)(nil).Stop), ctx, machineID, projectName)
}

// Up mocks base method.
func (m *MockCompose) Up(ctx context.Context, machineID, projectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Up", ctx, machineID, projectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Up indicates an expected call of Up.
func (mr *MockComposeMockRecorder) Up(ctx, machineID, projectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockCompose)(nil).Up), ctx, machineID, projectName)
}

// Update mocks base method.
func (m *MockCompose) Update(ctx context.Context, machineID, projectName, yamlContent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, machineID, projectName, yamlContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockComposeMockRecorder) Update(ctx, machineID, projectName, yamlContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCompose)(nil).Update), ctx, machineID, projectName, yamlContent)
}
